# This file enables submodules and configures all kinds of settings.

# Enable logging via the serial console
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
# Set this to y to get immediate logging instead of deferred logging. Might be useful for debugging.
CONFIG_LOG_MODE_IMMEDIATE=y

# Enable the environmental sensor and the magnetometer.
CONFIG_I2C=y
CONFIG_SENSOR=y

# Currently, we need to mock the I2C peripherals because of the new board revision.
CONFIG_MOCK_ENV_SENSORS=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_TIMER_RANDOM_GENERATOR=y

# Here, we can set the LED blink interval to different values.
CONFIG_BLINK_INTERVAL_MS=1000
